name       : perl-encode-jis2k
version    : 0.03
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DANKOGAI/Encode-JIS2K-0.03.tar.gz : 1ec84d72db39deb4dad6fca95acfcc21033f45a24d347c20f9a1a696896c35cc
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Encode::JIS2K - JIS X 0212 (aka JIS 2000) Encodings
description: |
    Encode::JIS2K - JIS X 0212 (aka JIS 2000) Encodings
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
